package smc.syntaxAnalyzer

enum SyntaxState:
  case
  MachineDeclaration,
  MachineValue,
  MachineNamed,
  InitialArrow,
  InitialArrowNamed,
  MachineSpec,
  InitialValue,
  InheritsValue,
  StateValue,
  EventArrow,
  EventValue,
  NextStateArrow,
  NextStateValue,
  ActionArrow,
  ActionDeclaration,
  ActionValue,
  SuperstateValue,
  SuperstateDeclaration,
  SubtransitionSpec,
  EntryDeclaration,
  EntryValue,
  ExitDeclaration,
  ExitValue,
  SubeventValue,
  SubNextStateArrow,
  SubNextStateValue,
  SubactionArrow,
  SubactionDeclaration,
  SubactionValue
