package smc.syntaxAnalyzer

enum SyntaxState:
  case Machine
  case MachineValue
  case MachineNamed
  case InitialArrow
  case InitialArrowNamed
  case MachineSpec
  case InitialValue
  case StateValue
  case EventArrow
  case EventValue
  case NextStateArrow
  case NextStateValue
  case ActionArrow
  case ActionDeclaration
  case ActionValue
  case SuperstateValue
  case SuperstateDeclaration
  case SubtransitionSpec
  case EntryValue
  case ExitValue
  case SubeventValue
  case SubNextStateArrow
  case SubNextStateValue
  case SubactionArrow
  case SubactionDeclaration
  case SubactionValue
  case End