package smc.semanticAnalyzer

enum SemanticError:
  case
  NO_MACHINES,
  DUPLICATE_MACHINE,
  NO_INITIAL_STATE,
  NO_TRANSITIONS,
  UNDEFINED_INITIAL_STATE,
  UNDEFINED_NEXT_STATE,
  UNUSED_STATE,
  DUPLICATE_STATE,
  DUPLICATE_TRANSITION,
  UNDEFINED_SUPER_STATE,
  SUPERSTATE_AS_NEXT_STATE,
  SUPERSTATE_CONFLICT
